/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Jesus
 */
public class VistaTrabajos extends javax.swing.JFrame {
FondoPanel fondo= new FondoPanel();
    /**
     * Creates new form VistaTrabajos
     */
    public VistaTrabajos() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Trabajos realizados por los empleados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tra = new javax.swing.JButton();
        btn_trh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablatrabajos = new javax.swing.JTable();
        btnregresart = new javax.swing.JButton();
        btn_tra2020 = new javax.swing.JButton();
        btn2021t = new javax.swing.JButton();
        combobox2020 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_tra.setBackground(new java.awt.Color(0, 102, 204));
        btn_tra.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        btn_tra.setForeground(new java.awt.Color(255, 255, 255));
        btn_tra.setText("TRABAJOS POR EL ING. ALEXIS CASTILLO");

        btn_trh.setBackground(new java.awt.Color(0, 102, 204));
        btn_trh.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        btn_trh.setForeground(new java.awt.Color(255, 255, 255));
        btn_trh.setText("TRABAJOS POR EL ING. HECTOR MERINO");
        btn_trh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trhActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel1.setText("TRABAJOS REALIZADOS EN LA EMPRESA");

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel2.setText("CASUNI S.A DE C.V");

        tablatrabajos.setBackground(new java.awt.Color(0, 102, 204));
        tablatrabajos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablatrabajos.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        tablatrabajos.setForeground(new java.awt.Color(255, 255, 255));
        tablatrabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SERIE", "NOMBRE", "APELLIDO", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(tablatrabajos);
        if (tablatrabajos.getColumnModel().getColumnCount() > 0) {
            tablatrabajos.getColumnModel().getColumn(0).setHeaderValue("SERIE");
            tablatrabajos.getColumnModel().getColumn(1).setHeaderValue("NOMBRE");
            tablatrabajos.getColumnModel().getColumn(2).setHeaderValue("APELLIDO");
            tablatrabajos.getColumnModel().getColumn(3).setHeaderValue("FECHA");
        }

        btnregresart.setBackground(new java.awt.Color(0, 102, 204));
        btnregresart.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        btnregresart.setForeground(new java.awt.Color(255, 255, 255));
        btnregresart.setText("REGRESAR");

        btn_tra2020.setBackground(new java.awt.Color(0, 102, 204));
        btn_tra2020.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        btn_tra2020.setForeground(new java.awt.Color(255, 255, 255));
        btn_tra2020.setText("TRABAJOS AÑO 2020");

        btn2021t.setBackground(new java.awt.Color(0, 102, 204));
        btn2021t.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        btn2021t.setForeground(new java.awt.Color(255, 255, 255));
        btn2021t.setText("TRABAJOS AÑO 2021");

        combobox2020.setBackground(new java.awt.Color(0, 102, 204));
        combobox2020.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        combobox2020.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobox2020, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tra2020, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(btn2021t, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_trh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnregresart)
                .addContainerGap(922, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(399, 399, 399))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_trh)
                    .addComponent(btn_tra2020))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tra)
                    .addComponent(btn2021t))
                .addGap(26, 26, 26)
                .addComponent(combobox2020, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnregresart)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_trhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTrabajos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn2021t;
    public javax.swing.JButton btn_tra;
    public javax.swing.JButton btn_tra2020;
    public javax.swing.JButton btn_trh;
    public javax.swing.JButton btnregresart;
    public javax.swing.JComboBox<String> combobox2020;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablatrabajos;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen=new ImageIcon(getClass().getResource("/Images/backwhite.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
